import { build } from 'vite';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const result = await build({
  root,
  configFile: false,
  logLevel: 'warn',
  build: {
    lib: { entry: resolve(root, 'src/main.js'), name: 'CalculusPractice', formats: ['iife'] },
    write: false,
    minify: true,
    cssCodeSplit: false,
  },
});

// Library mode embeds font assets and emits a classic script that works with file://.
const output = (Array.isArray(result) ? result : [result]).flatMap((bundle) => bundle.output);
const css = output.filter((file) => file.type === 'asset' && file.fileName.endsWith('.css')).map((file) => file.source).join('\n');
const js = output.filter((file) => file.type === 'chunk').map((file) => file.code).join('\n');
if (!css || !js || output.some((file) => file.type === 'asset' && !file.fileName.endsWith('.css'))) {
  throw new Error('Expected a self-contained script and stylesheet with all fonts embedded.');
}

const template = await readFile(resolve(root, 'src/index.html'), 'utf8');
const html = template
  .replace('<html', '<!-- Generated by npm run build. Edit src/index.html, src/main.js, or src/style.css. -->\n<html')
  .replace('</head>', () => `<style>\n${css}\n</style>\n  </head>`)
  .replace('<script type="module" src="./main.js"></script>', () => `<script>\n${js.replace(/<\/script/gi, '<\\/script')}\n</script>`);
await mkdir(resolve(root, 'dist'), { recursive: true });
await writeFile(resolve(root, 'dist/index.html'), html);
await writeFile(resolve(root, 'index.html'), html);
console.log('Built index.html and dist/index.html. Both open directly in a browser, including offline.');
